name: Discord Anti-Ads Bot

on:
  schedule:
    - cron: "0 */4 * * *"  # runs every 4 hours
  workflow_dispatch:

jobs:
   ru-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.D }}
        run: python -u Bot_test.py

   run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run the bot
        env:
          DISCORD_TOKEN: ${{ secrets.D }}
        run: python -u Bot.py
